settings:
  every-join-is-first-join: false

on-first-join:
  broadcast-message:
    enabled: true
    message: '&d%player_name% has joined for the first time!'
  kits:
    enabled: true
    items:
    - wood_sword
    - wood_pickaxe
    - wood_spade
    - wood_axe
    - bread:5
  written-books:
    enabled: false
    book-files:
    - rules.txt
  run-commands:
    enabled: false
    commands:
    - me just joined for the first time!
  run-console-commands:
    enabled: false
    commands:
    - setgroup %player_name newbies
  teleport:
    enabled: false
    x: 0
    y: 64
    z: 0
    pitch: 0
    yaw: 0
    world: world
